// 前端入口:StageOS 中国传统色色库(单一事实来源在 supabase/functions/_shared/palette-library.ts,
// 与 ai-generate-plan 边缘函数共用,保证 AI prompt 与前端配色候选使用同一套 853 色 + 70 方案数据)。
export {
  PALETTE_COLORS,
  PROGRAM_PRESETS,
  PALETTE_FORMULAS,
  PALETTE_SCENE_TYPES,
  PALETTE_STYLE_TAGS,
  PALETTE_COLOR_SOURCES,
  PALETTE_DISCLAIMER,
  PALETTE_VERSION,
  hexToRgb,
  rgbToOklab,
  oklabToHex,
  deltaE,
  oklabComplement,
  rgbToHsl,
  hslToHex,
  hslComplement,
  isLightColor,
  pickNearestColor,
  fillToFive,
  getPresetByName,
  getPresetForProgram,
  getPaletteForProgram,
  getProgramsBySceneType,
  getProgramsByStyleTag,
  retrievePresets,
  compilePresetContext,
} from "../../supabase/functions/_shared/palette-library";
export type {
  PaletteLibraryColor,
  PaletteColorEntry,
  PaletteFormula,
  ProgramPreset,
  ExtendedPaletteColor,
  RGB,
  OKLab,
  HSL,
} from "../../supabase/functions/_shared/palette-library";
